### ISSUE TITLE
Readme.md is outdated

### ISSUE THREAD

**Issue by ericlaw1979** [zmarty/double-shot-search#10]
`* This extension requires some advanced permissions to force Google to load in an iframe by modifying the X-Frame-Options header Google sends to the browser. We do NOT modify any other page in any other way.`

The extension modifies both the Bing and Google search results pages to inject an onmessage handler to handle resize/scroll. We may want to disclose that here, although perhaps we don't need to where we claim we don't modify anything else in the Chrome Web Store text.

`* This extension collects information on the searches issued from the extension. We do not collect information about any other pages or extensions. The data we collect is used exclusively for research to improve search engines. The information is used in aggregate and anonymously.`

As far as I can tell, the extension itself is not collecting information and that is claimed in the Chrome Web Store's Privacy Info. https://chrome.google.com/webstore/detail/double-shot-search-query/kddlkbpbepnaepdleclhdnfdpdogdhop/

**Comment by zmarty** [comment]
Both statements are now not true and can be removed. Will edit it shortly. Thanks Eric!
