### ISSUE TITLE
Web Link is linking/redirecting to a malware installing site.

### ISSUE THREAD

**Issue by dembeck** [zmarty/double-shot-search#2]
The link "www.doubleshotsearch.com" is redirecting to different subdomains like "ww1.doubleshotsearch.com/..." or "ww38.doubleshotsearch.com/..."

Your site has been compromised and is giving out malware through a JavaScript/iframe from iyfsearch com "http://iyfsearch.com/?dn= doubleshotsearch.com&pid=9PO755G95"

**Comment by zmarty** [comment]
Thanks. The code points to doubleshotsearch.download. The .com you see here on github was wrong (old domain). I fixed it.
