### ISSUE TITLE
BUG: Make x-frame-options only apply to Google.com

### ISSUE THREAD

**Issue by zmarty** [zmarty/double-shot-search#5]

**Comment by ericlaw1979** [comment]
Ideally, not just to Google.com, but also only to Google.com when being loaded in the context of the Search Extension's web page, not any arbitrary page.

In addition to this important security fix (which should've caused the extension to fail Store review), you'll also need to add the `extraHeaders` option for this extension to work in Chrome/Edge88+.

See https://bugs.chromium.org/p/chromium/issues/detail?id=1185393#c4
