### ISSUE TITLE
Google result is busted

### ISSUE THREAD

**Issue by crclayton** [zmarty/double-shot-search#8]
I'm using the Chromium Edge browser with version 2.4. In the last couple of days it looks like google has broken the extension:

![image](https://user-images.githubusercontent.com/6371270/110357528-3b60a480-7ff0-11eb-9cb3-54c29376fe7d.png)

Checking the console:

![image](https://user-images.githubusercontent.com/6371270/110357625-54695580-7ff0-11eb-8c5c-1f6ba6c8f9ed.png)

**Comment by ericlaw1979** [comment]
This is fixed in 2.5

**Comment by crclayton** [comment]
So it is! Thanks.

FYI the Edge Add-ons store has the latest version at 2.4: 

![image](https://user-images.githubusercontent.com/6371270/110379461-b5eaed80-800b-11eb-8fc1-ba1620d6f6ff.png)

But you're right, I was able to download 2.5 from the Chrome store and it's working.
